NuBusFPGAID = 0xBEEF

defMinorBase = 0 /*  beginning */
defMinorLength = 0xC0000 /*  768 KiB */

Pages8s = 1 /*  no idea */

defmBounds_Ts = 0
defmBounds_Ls = 0
defmBounds_Bs = 480
defmBounds_Rs = 640

DrHwNuBusFPGA = 0xBEEF /*  placeholder */

defmBaseOffset = 0 /*  beginning, placeholder */

devVersion = 0 /*  placeholder */

defmHRes = 0x480000 /* Horizontal Pixels/inch */
defmVRes = 0x480000 /* Vertical pixels/inch */

defmDevType = 0 /* 0 = CLUTType */

defmPlaneBytes	= 0 /* Offset from one plane to the next. */

SGammaResID = 0

RB8s = 640


ChunkyIndexed = 0

defVersion		=		0			/* Version = 0 */

ROMSize			=		0x1000					/* 4K byte ROM */

